### ISSUE TITLE
npm install -> Filed to compile

### ISSUE THREAD

**Issue by kreafik** [boidushya/boidushya.com#7]
Failed to compile.

 Module not found: Error: Can't resolve 'color' in '../src/styles'
ERROR in ./src/styles/theme.js 3:0-26
Module not found: Error: Can't resolve 'color' in '../src/styles'

webpack compiled with 1 error

**Comment by boidushya** [comment]
Have you tried doing yarn install or npm install beforehand first? This might be caused due to `craco-alias`
